theme: minima
title: The DevOps Runbook
author: Bob Clarke
email: bobmclarke@gmail.com
description: Notes about interesting challenges I’ve experienced in relation to containers at scale, automation, networking, encryption, monitoring, testing and generally trying to build and run robust production systems.
github_username: bobclarke
linkedin_username: bobmclarke 